# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kubes-proj
  labels:
#    type: restapi
spec:
  selector:
    matchLabels:
      app: flask-kubes-proj
  replicas: 2
  template:
    metadata:
#      name: flask-kubes-proj-tmpl
      labels:
        app: flask-kubes-proj
    spec:
      containers:
        - name: flask-kubes-proj
          image: flask-kubes-proj:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: flask-kubes-proj
spec:
  type: LoadBalancer
  selector:
    app: flask-kubes-proj
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
