apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app  # Change the label from "run" to "app"
  template:
    metadata:
      labels:
        app: flask-app  # Change the label from "run" to "app"
    spec:
      containers:
      - name: flask-app
        image: smaraba/flask-kubes-proj:latest  # Updated image name
        ports:
        - containerPort: 5000 # Port on which docker container listens on
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
