apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-kubes-proj-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-kubes-proj-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
