---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app  # Change the label from "run" to "app"
spec:
  selector:
    app: flask-app  # Change the label from "run" to "app"
  type: LoadBalancer  # Use NodePort to expose the service externally
  ports:
    - port: 32001  # Expose the service on a NodePort (adjust as needed)
      nodePort: 32001
      targetPort: 5000 # Port on which deployment port (listed above)
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Adjust the target CPU utilization percentage
